//
// Created by Administrator on 2023/7/26.
//

#ifndef TINYALSA_DEMO_CONSTS_H
#define TINYALSA_DEMO_CONSTS_H

#define STATUS_UNPLAY 1
#define STATUS_PLAYING 2
#define STATUS_PAUSE 3
#define STATUS_COMPLETE 4
#define STATUS_PLAYER_UNINIT -1
#define PLAY_SUCCESS 1
#define PLAY_FAIL -1

#endif //TINYALSA_DEMO_CONSTS_H
